build_info: 'Gigantum Client :: 2019-07-20 :: c21042b3'
created_on: '2019-07-23T18:43:49.938087'
description: An exploration of NLP workshops from around the internet
id: b7e4ab4c425d497189d8b54f650f0bad
name: nlp-workshop-expo
schema: 2
